In [8]:
import numpy as np
arr=np.arange(1,21,1,dtype=int)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(20,)
20
int64


In [26]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(50,size=(4,5))
print(arr)
print(arr.itemsize)
print(arr.nbytes)

[[37 43 12  8  9]
 [11  5 15  0 16]
 [ 1 12  7 45  6]
 [25 20 37 18 20]]
4
80


In [37]:
import numpy as np
arr=np.random.randint(50,size=(3,4))
print(arr)
print(arr[:2,:])
print(arr[:,::-2])




[[32 12  1 30]
 [41 24 18 33]
 [ 2 44 28 39]]
[[32 12  1 30]
 [41 24 18 33]]
[[30 12]
 [33 24]
 [39 44]]


In [ ]:
import numpy