In [6]:
import numpy as np
name=['alice','bob','cathy','doug']
age=[25,45,37,19]
weight=[55.0,85.5,68.0,61.5]

data=np.zeros(
    4,
    dtype={
        'names':('name','age','weight'),
        'formats':('U10','i4','f8')
    }
)
print("structured array using a compound data type")
print(data.dtype)

data['name']=name
data['age']=age
data['weight']=weight

print("filled structured array")
print(data)

print("all names")
print(data['name'])
print("first row of data")
print(data[-1]['name'])

print("names where age is under 30")
print(data[data['age']<30]['name'])

#dictionary method
np.dtype({
     'names':('name','age','weight'),
        'formats':('U10','i4','f8')
})

np.dtype({
    'names':('name','age','weight'),
    'formats':((np.str_,10),int,np.float32)
})

np.dtype([
    ('name','S10'),
    ('age','i4'),
    ('weight','f8')
])

np.dtype('S10,i4,f8')


structured array using a compound data type
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
filled structured array
[('alice', 25, 55. ) ('bob', 45, 85.5) ('cathy', 37, 68. )
 ('doug', 19, 61.5)]
all names
['alice' 'bob' 'cathy' 'doug']
first row of data
doug
names where age is under 30
['alice' 'doug']


dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [10]:
import numpy as np

tp=np.dtype([
    ('id','i8'),
     ('mat','f8',(3,3))
])
X=np.zeros(1,dtype=tp)

print(X[0])
print(X['mat'][0])

(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
data_rec=data.view(np.recarry)
print(data_rec.age)

%timeit data['age']
%timeit data_rec['age']

%timeit data
